### ISSUE TITLE
IOC Lookup Failed

### ISSUE THREAD

**Issue by devotox** [zakodium/adonis-apollo#22]
![Screenshot 2020-12-09 at 17 53 52](https://user-images.githubusercontent.com/2064846/101667668-8433ac00-3a47-11eb-9090-d7c69f5f27fa.png)

**Comment by devotox** [comment]
```
import Route from '@ioc:Adonis/Core/Route'
import ApolloServer from '@ioc:ApolloServer'

ApolloServer.applyMiddleware({ Route })
Route.get('/', async() => ({ hello: 'world' }))

```

**Comment by devotox** [comment]
I think this works `import ApolloServer from '@ioc:Apollo/Server'`

**Comment by targos** [comment]
Yeah, this is a mistake in the README. Would you like to open a PR to fix it?

**Comment by devotox** [comment]
Love to!

**Comment by devotox** [comment]
@targos PR opened, Also do you know how to force Adonis to reload when graphql file changes?

**Comment by targos** [comment]
Thanks for the PR. To force Adonis to reload, add this to `.adonisrc.json`, in the `metaFiles` array:

```json
    {
      "pattern": "app/Schemas/*",
      "reloadServer": true
    }
```
