### ISSUE TITLE
Validation is run twice

### ISSUE THREAD

**Issue by stropitek** [zakodium/adonis-apollo#26]
![image](https://user-images.githubusercontent.com/4118690/106890902-458a3d00-66ea-11eb-9f9a-7646e8e3da38.png)

This output is confusing because you cannot tell that adonis-apollo ran the validation of the schema twice and only the last error is valid. This happens not only when starting the server for the first time, but also when restarting the server after source files changed.

I don't know adonis well enough to understand why this code seems to be running before the compilation finished. Is this the expected behavior?

**Comment by targos** [comment]
This happened because a resolver imported the GraphQL server while it was being constructed. We cannot support that, so either we close this issue or try to detect the case and throw with a meaningful error when it happens.
