### ISSUE TITLE
Remove Playground in Prod Env

### ISSUE THREAD

**Issue by devotox** [zakodium/adonis-apollo#32]
It does not look like there is a way to disable the playground atm

**Comment by targos** [comment]
There is a way if you directly use the `get...Handler` methods instead of `applyMiddleware`. That said, what do you think about a new config value to enable/disable the playground?
Would you like to add it?

**Comment by targos** [comment]
Done in https://github.com/zakodium/adonis-apollo/commit/2b07ac0067b2f7a0ce73983125301d45b82b1020
