### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by bingalls** [zakodium/adonis-apollo#5]
I am starting with a fresh Adonis v5.0.9 install. I got as far as `npm i adonis-apollo --save`
After that, I could not run `node ace invoke ...`. it looks that invoke must be deprecated.
Perhaps because of this, there is no `app/Schemas/` directory, nor could I find one in this repo.
Note also that your closed issue points to a dead link.
Finally, npm install yields warnings, likely because package.json still uses a preview version.

Tested using latest @adonis/cli v3.2.1 on both node v12 & v14

**Comment by targos** [comment]
This module is only compatible with the next version of AdonisJS (https://preview.adonisjs.com/)

**Comment by bingalls** [comment]
@targos Your README needs prerequisite requirements.
My environment is Mac OSX Catalina 10.15 running nodejs v14.11.0.
I think we need newer than the minimum versions in https://preview.adonisjs.com/ to support node modules. As well, typescript must be installed globally (shortcoming of Adonis docs)
It looks necessary to `npm un -g @adonis/cli` as well as `rm -fr /usr/local/lib/node_modules/@adonis`
Please add the initial step of creating an **API Server** following the steps at https://preview.adonisjs.com/ (until the main Adonis site supports v5)
Since you don't yet support graphiql, it will still be a challenge to figure out the syntax for schemas & resolvers, without an example. That would be a new issue; in the mean time, I hope to build such an example.
Thanks for your help, for moving this forward!
