### ISSUE TITLE
Support dependency injection in resolvers

### ISSUE THREAD

**Issue by targos** [zakodium/adonis-apollo#50]
It means detecting if a resolver was exported as a default class and use the IoC container to instantiate it.

**Comment by targos** [comment]
After discussing with @stropitek, here's the proposal:

## Proposal

- Keep support for current API (default-exported object of types and their resolvers), which can be used together with the new one in the same project.
- If a class constructor is exported, it must be a named export, the name (of the export) being the GraphQL type name. To help avoid name clashes, support classes with a name suffix of `Resolvers`.
- Each method on the class' prototype is a resolver for a field with the method's name
- Internally, `adonis-apollo` will construct the class once using the Adonis IoC container (to allow for dependency injection at the constructor level), and construct a resolvers object with wrapper functions that forward the GraphQL call to a call of the class methods (with `this` bound as expected).

## Example

### Previous API

```js
const resolvers = {
  Query: {
    hello() {
      return 'world';
    },
    rectangle(_, args) {
      return {
        width: args.width,
        height: args.height,
      };
    }
  },
  Rectangle: {
    area(rectangle) {
      return rectangle.width * rectangle.height;
    },
  }
}

export default resolvers;
```

### New API

```js
import type Rectangle from 'somewhere';

export class Query {
  hello() {
    return 'world';
  }

  rectangle(_, args) {
    return {
      width: args.width,
      height: args.height,
    };
  }
}

export class RectangleResolvers {
  area(rectangle: Rectangle) {
    return rectangle.width * rectangle.height;
  }
}
```

**Comment by tpoisseau** [comment]
> adonis-apollo will construct the class once using the Adonis IoC container

You mean once by request or, once for all application ?

about mutation, it would be something similar to

```ts
export class Mutation {
  async createRectangle(_, args) {
    await validation(args);
    return saveInDB(args);
  }
}

?

And I'm worry about typing, the actual implementation rely on generated `GqlResolvers` type, the typing validations errors are local to functions, will it be the same on a class context ? TS will not set the error on class instead methods ?

I think the solution is to do something like this :

```ts
export class Query implements GqlQueryResolvers {

}
```

What about exhaustiveness of implementation ? generated gql types are partial, for merging implementation, but I'm not sure if we have error (at least at runtime) if some resolvers are missing.

**Comment by targos** [comment]
> You mean once by request or, once for all application ?

I mean once per application, but I'm open to once per request if Apollo allows it. I'm not sure it does, though. The request-specific stuff should be passed through the third argument of resolvers (graphql context).

> about mutation, it would be something similar to

Yes.

> And I'm worry about typing,

For typing, yes you can use `implements`, we tried it. There are validations in place in this package for exhaustiveness of `Query` and `Mutation` resolvers (after merging). It doesn't make sense to be exhaustive for other types because we don't know which field needs a resolver (many can just be read from the object directly).

**Comment by tpoisseau** [comment]
Ok
